// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace M000.Models;

public partial class Kurse
{
    [Key]
    [Column("ID")]
    public int ID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string KursName { get; set; }

    public int? DauerInTagen { get; set; }

    public byte? Aktiv { get; set; }

    [InverseProperty("Kurs")]
    public virtual ICollection<KursInhalte> KursInhalte { get; set; } = new List<KursInhalte>();
}